import type { Metadata } from "next";
import { Cinzel, Oswald } from "next/font/google";
import "./globals.css";

// 1. Configure the fonts
const cinzel = Cinzel({
  subsets: ["latin"],
  variable: "--font-rithi", // Must match CSS variable name
  // display: "swap",
});

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald", // Must match CSS variable name
  // display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 2. Add both font variables to the body className */}
      <body
        className={`${cinzel.variable} ${oswald.variable} antialiased bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  );
}